title: CHIJ St. Joseph's Convent
url: https://chijstjosephsconvent.moe.edu.sg
favicon: /images/Homepage/CHIJ Crest 2014_clear background_PNG format_2014.png
colors:
  primary-color: "#0a3885"
  secondary-color: "#09767d"
  media-colors:
    - title: media-color-one
      color: "#9e186a"
    - title: media-color-two
      color: "#4a90e2"
    - title: media-color-three
      color: "#50e3c2"
    - title: media-color-four
      color: "#d0021b"
    - title: media-color-five
      color: "#f97f6e"
description: Welcome to the official website of CHIJ St. Joseph's Convent.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1hqt5tjan22cd.amplifyapp.com
prod: https://master.d1hqt5tjan22cd.amplifyapp.com
shareicon: /images/Homepage/hero2.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: resources
google_analytics_ga4: ""
